### ISSUE TITLE
This repository is empty?

### ISSUE THREAD

**Issue by ghost** [IlSocio/Symbian-RomPatcherPlus#1]
Would you add source to this repository? Also, may you add license to all repositories?

Thank you for open-source *"Symbian Toys"*!

FTR, Here is original RomPatcher repo:

- https://github.com/zorn-v/ROMPatcher

And here are LCG's open-source apps mirrors (I'm not affiliated with LCG):

- https://github.com/Symbian9/X-plore_free
- https://github.com/Symbian9/ProfiMail_free

**Comment by IlSocio** [comment]
Hello @Symbian9,
I just added the RP+ sources and license :)

**Comment by ghost** [comment]
Thank You!
